services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    ports:
      - 11434:11434
    expose:
      - 11434
    volumes:
      - ollama:/root/.ollama
  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    expose:
      - 7860
    networks:
      - net
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant-data:/qdrant/storage




configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  mongo-data:
    driver: local
  qdrant-data:
    driver: local
  ollama:
    driver: local

networks:
  net:
