FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

RUN pip install --no-cache-dir python-dotenv==1.0.1 langchain==0.3.10 langchain-community==0.3.10 \
qdrant-client==1.12.1 gradio==5.8.0 pymongo==4.10.1 requests==2.32.3 bs4==0.0.2 ipykernel==6.29.5 ipython==8.27.0 \
ipywidgets==8.1.5 jupyter==1.1.1 jupyter-client==8.6.2 jupyter-console==6.6.3 jupyter-core==5.7.2 jupyter-server==2.14.2 \
jupyter-events==0.10.0 jupyter-lsp==2.2.5 jupyter-server-terminals==0.5.3 jupyterlab==4.2.5 jupyterlab-pygments==0.3.0 \
jupyterlab-quarto==0.3.5 jupyterlab-server==2.27.3 jupyterlab-widgets==3.0.13 langchain-openai==0.2.11 clearml==1.16.4